version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      nestjs:
        patterns: ["@nestjs/*"]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
